Fix AttributeError for "sfputil show error-status -hw"
When insert trasnceiver which is not QSFP-DD, "sfputil show error-status -hw" would fail
error:
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform_base/sonic_xcvr/sfp_optoe_base.py", line 211, in get_error_description
    return api.get_error_description() if api is not None else None
AttributeError: 'Sff8636Api' object has no attribute 'get_error_description'

Signed-off-by: chiourung_huang <chiourung_huang@edge-core.com>